# ==================================
# Couchdb
# ==================================
FROM couchdb:latest 
MAINTAINER Mikael Kall <kall.micke@gmail.com>

COPY ./bootstrap /bootstrap
COPY ./docker-entrypoint.sh /

WORKDIR /opt/couchdb
EXPOSE 5984 4369 9100
VOLUME ["/opt/couchdb/data"]

ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]
CMD ["/opt/couchdb/bin/couchdb"]
